flags:
  liquid-fixpoint:
    devel: true
  liquidhaskell:
    devel: true


packages:
- ./prover 
- ./liquid-fixpoint
- ./liquiddesugar
- '.'
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
compiler-check: newer-minor
resolver: nightly-2016-05-21
