flags:
  liquidhaskell:
    devel: true
  liquid-platform:
    devel: true
  tests:
    stack: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
packages:
- liquid-fixpoint
- liquid-ghc-prim
- liquid-base
- liquid-bytestring
- liquid-prelude
- liquid-vector
- liquid-containers
- liquid-parallel
- liquid-platform
- tests
- tests/benchmarks/popl18/lib
- .
extra-deps:
- hashable-1.3.0.0
- git: https://github.com/facundominguez/rest
  commit: 31e974979c90e910efe5199ee0d3721b791667f6
# for tests
- strip-ansi-escape-0.1.0.0@sha256:08f2ed93b16086a837ec46eab7ce8d27cf39d47783caaeb818878ea33c2ff75f,1628

resolver: lts-18.27
compiler: ghc-8.10.7

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
