flags:
  liquidhaskell:
    devel: true
  tests:
    stack: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
  liquidhaskell-boot: -j
  liquidhaskell: -j
packages:
- liquid-fixpoint
- liquid-prelude
- liquid-vector
- liquid-parallel
- liquidhaskell-boot
- tests
- tests/benchmarks/popl18/lib
- benchmark-timings
- .
extra-deps:
- rest-rewrite-0.4.3
- smtlib-backends-0.3@rev:2
- smtlib-backends-process-0.3@rev:2
- store-0.7.18
- store-core-0.4.4.6
- git: https://github.com/qnikst/ghc-timings-report
  commit: 45ef3498e35897712bde8e002ce18df6d55f8b15
- bytestring-0.12.0.2@sha256:9fc077ff5b7ed2246773c3ac4370ef8822e4834d4587522b68ae551a5968fb86,7891
- containers-0.6.8@sha256:bb2bec1bbc6b39a7c97cd95e056a5698ec45beb5d8feb6caae12af64e4bd823c,2670
- ghc-9.8.2@sha256:ef8d8751c9a4c0a07760b310c6c30bfc35d876b87c3bc8027a2a547cd5087716,26479


allow-newer: true
allow-newer-deps:
  - ghc-timings
  - colonnade
  - blaze-colonnade
  - blaze-svg
  - store-core

resolver: nightly-2024-05-14

nix:
  packages: [cacert, git, hostname, nix, stack, z3]
  path: [nixpkgs=./nixpkgs.nix]
