flags:
  liquidhaskell:
    devel: true
  liquid-platform:
    devel: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
packages:
- liquid-fixpoint
- liquid-ghc-prim
- liquid-base
- liquid-bytestring
- liquid-prelude
- liquid-vector
- liquid-containers
- liquid-parallel
- liquid-platform
- .
extra-deps:
- hashable-1.3.0.0
- git: https://github.com/facundominguez/rest
  commit: 31e974979c90e910efe5199ee0d3721b791667f6
- git: https://github.com/facundominguez/stitch-lh
  commit: 8e130a40376cdf9afaeb6e3e4322e1069339bb51

resolver: lts-18.27
compiler: ghc-8.10.7

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
