# GHC 7.10
resolver: nightly-2015-09-24

packages:
- ./prover
- ./liquid-fixpoint
- .

flags:
  liquid-fixpoint:
    build-external: true

extra-deps:
- intern-0.9.1.4
- located-base-0.1.0.0
- ascii-progress-0.3.2.0
- concurrent-output-1.7.1
- daemons-0.2.1
- ghc-opts-0.1.0.0
