
# resolver: nightly-2017-10-06
resolver: lts-10.0

packages:
- liquid-fixpoint/
- '.'

extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.1

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []
