flags:
  liquidhaskell:
    devel: true
  tests:
    stack: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
  liquidhaskell-boot: -j
  liquidhaskell: -j
packages:
- liquid-fixpoint
- liquid-prelude
- liquid-vector
- liquid-parallel
- liquidhaskell-boot
- tests
- tests/benchmarks/popl18/lib
- benchmark-timings
- .
extra-deps:
- rest-rewrite-0.4.3
- smtlib-backends-0.3@rev:2
- smtlib-backends-process-0.3@rev:2
- store-0.7.18
- store-core-0.4.4.6
- git: https://github.com/qnikst/ghc-timings-report
  commit: 45ef3498e35897712bde8e002ce18df6d55f8b15

allow-newer: true
allow-newer-deps:
  - ghc-timings
  - colonnade
  - blaze-colonnade
  - blaze-svg
  - store-core

resolver: nightly-2024-01-26

nix:
  packages: [cacert, git, hostname, nix, stack, z3]
  path: [nixpkgs=./nixpkgs.nix]
