flags:
  liquidhaskell:
    devel: true
  liquid-platform:
    devel: true
  tests:
    stack: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
packages:
- liquid-fixpoint
- liquid-ghc-prim
- liquid-base
- liquid-bytestring
- liquid-prelude
- liquid-vector
- liquid-containers
- liquid-parallel
- liquid-platform
- tests
- tests/benchmarks/popl18/lib
- benchmark-timings
- .
extra-deps:
- blaze-colonnade-1.2.2.1@sha256:b27601f0366b006e86ee33297a722fe33c94ac058e61d4eace387d132e656a21,1394
- colonnade-1.2.0.2@sha256:e0b43a1fe4f87072f3f7cd9eaccdb790f7df8ceff5f73c3a4e242aba9337485f,2099
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- git: https://github.com/qnikst/ghc-timings-report
  commit: 45ef3498e35897712bde8e002ce18df6d55f8b15
# for tests
- strip-ansi-escape-0.1.0.0@sha256:08f2ed93b16086a837ec46eab7ce8d27cf39d47783caaeb818878ea33c2ff75f,1628

resolver: lts-18.27

nix:
  packages: [cacert, git, hostname, z3]
  path: [nixpkgs=./nixpkgs.nix]
