flags:
  liquid-platform:
    devel: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
allow-newer: true # 8.10.1
packages:
- liquid-fixpoint
- liquid-ghc-prim
- liquid-base
- liquid-bytestring
- liquid-prelude
- liquid-vector
- liquid-containers
- liquid-parallel
- liquid-platform
- .
extra-deps:
- tasty-rerun-1.1.14
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1
- hashable-1.3.0.0
- optics-0.3
- optics-core-0.3
- optics-th-0.3
- optics-extra-0.3
- Diff-0.4.0
- aeson-1.4.7.1
- th-compat-0.1
- store-0.7.11
- store-core-0.4.4.4
- th-utilities-0.2.4.3
- th-abstraction-0.4.2.0

resolver: lts-16.8
compiler: ghc-8.10.2

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
