resolver: lts-12.26

packages:
- ../liquid-fixpoint/
- '.'

extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- tasty-rerun-1.1.12
- text-format-0.3.2

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []
