---
version: 2.1

commands:
  setup_project:
    description: "Setup the machine, clone the repo, checkout the submodules."
    steps:
      - run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq curl git ssh unzip wget libtinfo-dev gcc make
      - run:
          name: Install z3
          command: |
            # Config version
            z3version="z3-4.15.1"
            z3distributiontype="x64-glibc-2.39"
            z3full="${z3version}-${z3distributiontype}"

            # Download and install
            wget    "https://github.com/Z3Prover/z3/releases/download/${z3version}/${z3full}.zip"
            unzip   "${z3full}.zip"
            rm -f   "${z3full}.zip"
            sudo cp "${z3full}/bin/libz3.a" /usr/local/lib
            sudo cp "${z3full}/bin/z3"      /usr/local/bin
            sudo cp "${z3full}/include/"/*  /usr/local/include
            rm -rf  "${z3full}"
            z3 --version

      - run:
          name: Install cvc5
          command: |
            wget https://github.com/cvc5/cvc5/releases/download/cvc5-1.2.1/cvc5-Linux-x86_64-static.zip
            unzip cvc5-Linux-x86_64-static.zip
            rm -f cvc5-Linux-x86_64-static.zip
            sudo cp cvc5-Linux-x86_64-static/bin/cvc5 /usr/local/bin
            rm -rf cvc5-Linux-x86_64-static
            cvc5 --version

      - checkout
      - add_ssh_keys
      - run: git submodule sync
      - run: git submodule update --init

  cabal_build_and_test:
    description: "Build the project and run the tests"
    parameters:
      ghc_version:
        type: string
      extra_test_flags:
        type: string
        default: ""
      ghc_options:
        type: string
        default: "--ghc-options=\"+RTS -M2G -RTS\""
    steps:
      - setup_project
      - run: git ls-tree HEAD liquid-fixpoint > liquid-fixpoint-commit
      - run:
          name: Configure the build
          command: |
            wget https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup
            chmod +x ./x86_64-linux-ghcup
            ./x86_64-linux-ghcup install ghc << parameters.ghc_version >>
            ./x86_64-linux-ghcup set ghc << parameters.ghc_version >>
            ./x86_64-linux-ghcup install cabal 3.16.0.0
            export PATH=~/.ghcup/bin:$PATH
            echo 'export PATH=~/.ghcup/bin:$PATH' >> $BASH_ENV
            cabal update
            cabal configure --enable-tests
            cabal build all --dry-run
      - restore_cache:
          keys:
            - cabal-cache-v11-{{ checksum "dist-newstyle/cache/plan.json" }}
      - run:
          name: Dependencies
          command: |
            cabal build -j --only-dependencies liquidhaskell-boot
      - save_cache:
          key: cabal-cache-v11-{{ checksum "dist-newstyle/cache/plan.json" }}
          paths:
            - ~/.cache/cabal/packages
            - ~/.local/state/cabal/store
            - dist-newstyle
      - run:
          name: Test
          command: |
            mkdir -p /tmp/junit/cabal
            scripts/test/test_plugin.sh -- --ghc-options=-j1 -j1
            cabal test tests:tasty
            cabal test tests:liquidhaskell-test
            (cabal test -j1 liquidhaskell-boot --flag devel --test-show-details=streaming --test-options="--xml=/tmp/junit/cabal/parser-test-results.xml")
          no_output_timeout: 30m

      - run:
          name: Test building the profiling driver
          command: |
            cabal build --enable-profiling --flag devel scripts/profiling-driver

jobs:

  cabal_ghc_9141:
    machine:
      image: ubuntu-2404:2025.09.1
    steps:
      - cabal_build_and_test:
          ghc_version: "9.14.1"

workflows:
  version: 2
  build_stack_and_cabal:
    jobs:
      - cabal_ghc_9141
