cabal-version:      1.24
name:               liquid-finfield
version:            0.9.12.2.1
synopsis:           Finite field utilities for LiquidHaskell (requires cvc5)
description:        Finite field utilities for LiquidHaskell (requires cvc5)
license:            BSD3
license-file:       LICENSE
copyright:          2010-19 Ranjit Jhala & Niki Vazou & Eric L. Seidel, University of California, San Diego.
author:             Alex Gryzlov, Niki Vazou
maintainer:         Ranjit Jhala <jhala@cs.ucsd.edu>
category:           Language
homepage:           https://github.com/ucsd-progsys/liquidhaskell
build-type:         Simple

library
  exposed-modules:  Language.Haskell.Liquid.FinField
                    Language.Haskell.Liquid.FinField.FF17
  hs-source-dirs:     src
  build-depends:      base          < 5
                    , liquidhaskell        >= 0.9.12.2.1
  default-language:   Haskell2010
