name: whitespace

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: andreasabel/fix-whitespace-action@v1
        with:
          version:    0.1
          configfile: fix-whitespace.yaml
          fix:        false
          verbose:    true
